"""Schedule

Revision ID: 02eacee2dbd2
Revises: 6f3c82d8656f
Create Date: 2025-01-10 10:44:51.773035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eacee2dbd2'
down_revision = '6f3c82d8656f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='daysofweek'),
               existing_nullable=False)
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))
        batch_op.alter_column('day_of_week',
               existing_type=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='daysofweek'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('time')

    # ### end Alembic commands ###
