"""Initial migration

Revision ID: 3f69257105f7
Revises: 
Create Date: 2025-01-05 13:07:10.633100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f69257105f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_code'), ['code'], unique=True)
        batch_op.drop_column('schedule')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_course', ['user_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_course', type_='unique')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_index(batch_op.f('ix_course_code'))

    op.drop_table('payout_history')
    # ### end Alembic commands ###
