"""aaa

Revision ID: 745412834b5d
Revises: 
Create Date: 2025-01-27 21:32:37.930079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745412834b5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:

        batch_op.create_foreign_key('fk_enrollment_course_id', 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_enrollment_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:

        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
